<?php

/**
 * @file
 * Provides media integration for Instagram posts.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_cron().
 */
function media_instagram_cron() {
  $queue = \Drupal::queue('media_instagram_fetch');

  /** @var \Drupal\media\MediaTypeInterface[] $bundles */
  $bundles = \Drupal::entityTypeManager()
    ->getStorage('media_type')
    ->loadByProperties(['source' => 'instagram']);
  foreach ($bundles as $bundle) {
    $queue->createItem($bundle);
  }

  $state = \Drupal::state();
  $token = $state->get('media_instagram.token');

  if ($token && $token['refresh'] - \Drupal::time()->getRequestTime() < 0) {
    $refreshed_token = \Drupal::service('media_instagram.instagram_fetcher')->refreshToken($token['token']);
    if ($refreshed_token) {
      $state->set('media_instagram.token', [
        'token' => $refreshed_token['access_token'],
        // Set refresh timestamp, ¾ before token expires to give a time buffer
        // in case a refresh request fails, thus giving more opportunities in
        // future cron runs.
        'refresh' => \Drupal::time()->getRequestTime() + floor($refreshed_token['expires_in'] * 0.75),
      ]);
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function media_instagram_media_type_delete(EntityInterface $entity) {
  \Drupal::state()->delete("media_instagram.{$entity->id()}.since");
}
